name: Deploy static site to Azure Web App

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload files to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: mlsaproject   # your Web App name
        package: .              # deploy everything in repo root (index.html, css, js)
